# hello-kubernetes.custom-message.yaml
apiVersion: v1
kind: Service
metadata:
  name: greet-user
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: greet-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greet-user
  template:
    metadata:
      labels:
        app: greet-user
    spec:
      containers:
      - name: greet-kubernetes
        image: $registry:$BUILD_NUMBER
        ports:
        - containerPort: 8080
